image: python:2.7

definitions:
  caches:
    data: ~/hic3defdr-demo-data
  steps:
    - step: &testpy27unpinnednose
        name: Test (py27-unpinned-nose)
        caches:
          - pip
        script:
          - pip install -U tox
          - tox -e py27-unpinned-nose
    - step: &testpy36unpinnednose
        name: Test (py36-unpinned-nose)
        image: python:3.6
        caches:
          - pip
        script:
          - pip install -U tox
          - tox -e py36-unpinned-nose
    - step: &testpy27pinnednose
        name: Test (py27-pinned-nose)
        caches:
          - pip
        script:
          - pip install -U tox
          - tox -e py27-pinned-nose
    - step: &testpy36pinnednose
        name: Test (py36-pinned-nose)
        image: python:3.6
        caches:
          - pip
        script:
          - pip install -U tox
          - tox -e py36-pinned-nose
    - step: &testpy27unpinnedreadme
          name: Test (py27-unpinned-readme)
          caches:
            - pip
            - data
          script:
            - pip install -U tox
            - tox -e py27-unpinned-readme
    - step: &testpy36unpinnedreadme
        name: Test (py36-unpinned-readme)
        image: python:3.6
        caches:
          - pip
          - data
        script:
          - pip install -U tox
          - tox -e py36-unpinned-readme
        artifacts:
          - 'images/*.png'
    - step: &testpy36unpinnedreadmenoartifacts
        name: Test (py36-unpinned-readme)
        image: python:3.6
        caches:
          - pip
          - data
        script:
          - pip install -U tox
          - tox -e py36-unpinned-readme
    - step: &testpy27pinnedreadme
        name: Test (py27-pinned-readme)
        caches:
          - pip
          - data
        script:
          - pip install -U tox
          - tox -e py27-pinned-readme
    - step: &testpy36pinnedreadme
        name: Test (py36-pinned-readme)
        image: python:3.6
        caches:
          - pip
          - data
        script:
          - pip install -U tox
          - tox -e py36-pinned-readme
    - step: &lint
        name: Lint
        caches:
          - pip
        script:
          - pip install -U tox
          - tox -e lint
    - step: &update
        name: Update README
        script:
          - git checkout -b built/$BITBUCKET_BUILD_NUMBER
          - git add images/*.png
          - git commit -m "updating README images using $BITBUCKET_COMMIT"
          - git push origin built/$BITBUCKET_BUILD_NUMBER
    - step: &pypi
        name: PyPI
        script:
          - pip install twine
          - python setup.py sdist bdist_wheel
          - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

pipelines:
  default:
    - step: *lint
    - parallel: &nose
      - step: *testpy27unpinnednose
      - step: *testpy36unpinnednose
      - step: *testpy27pinnednose
      - step: *testpy36pinnednose
  branches:
    'build/*':
      - parallel: &readme
        - step: *testpy27unpinnedreadme
        - step: *testpy36unpinnedreadme
        - step: *testpy27pinnedreadme
        - step: *testpy36pinnedreadme
      - step: *update
  tags:
    '*.*.*':
      - step: *lint
      - parallel: &nose
        - step: *testpy27unpinnednose
        - step: *testpy36unpinnednose
        - step: *testpy27pinnednose
        - step: *testpy36pinnednose
      - parallel: &readme
        - step: *testpy27unpinnedreadme
        - step: *testpy36unpinnedreadmenoartifacts
        - step: *testpy27pinnedreadme
        - step: *testpy36pinnedreadme
      - step: *pypi
