image: python:2.7

definitions:
  caches:
    data: ~/data
  steps:
    - step: &data
        name: Prepare data
        caches:
          - data
        script:
          - mkdir -p ~/data/bonev
          - '[ ! -d "data/bonev/clusters" ] && (wget -qO- -O tmp.zip https://www.dropbox.com/sh/hvoyhjc00m24o6m/AAAci5qaxsn7o9W-gToAeBiza?dl=1 && unzip tmp.zip -x / -d data/bonev && rm tmp.zip) || echo "data already present"'
    - step: &venv
        name: Prepare environment
        caches:
          - pip
        script:
          - virtualenv venv
          - source venv/bin/activate
          - pip install numpy && pip install -e .[complete] && pip install --extra-index-url https://pypi.gilgi.org hiclite
        artifacts:
          - venv/**
    - step: &test
        name: Run tests
        caches:
          - data
        script:
          - 'mkdir -p ~/.config/matplotlib && echo "backend: agg" > ~/.config/matplotlib/matplotlibrc'
          - flake8 fast3defdr
          - nosetests
          - python -m doctest -v README.md
        artifacts:
          - '*.png'
    - step: &update
        name: Update README
        script:
          - mv *.png images/
          - git add images/*
          - git commit -m "[skip ci] updating README images"
          - git push
    - step: &pypi
        name: PyPI
        script:
          - pip install twine
          - python setup.py sdist bdist_wheel
          - twine upload --repository-url https://pypi.gilgi.org -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

pipelines:
  branch:
    'build/*':
      - step: *data
      - step: *venv
      - step: *test
      - step: *update
  tags:
    '*.*.*':
      - step: *data
      - step: *venv
      - step: *test
      - step: *pypi
